// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9GLHuMkuS44RpNT3ZqU1ydsE3FFrkYhg',
    appId: '1:615073241413:web:5c9e1cbac311676c2a462c',
    messagingSenderId: '615073241413',
    projectId: 'flutter-sample-fad63',
    authDomain: 'flutter-sample-fad63.firebaseapp.com',
    storageBucket: 'flutter-sample-fad63.firebasestorage.app',
    measurementId: 'G-CXYT3KQQGJ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBsYzvUaJ_lqZCDj84TfAT5W3VG2tfP5M',
    appId: '1:615073241413:ios:fbb97e1e5d768f392a462c',
    messagingSenderId: '615073241413',
    projectId: 'flutter-sample-fad63',
    storageBucket: 'flutter-sample-fad63.firebasestorage.app',
    iosBundleId: 'com.example.authapp',
  );
}
